#!/bin/bash

export LANG=en_US.UTF-8
export LC_ALL=en_US.URF-8

COMMIT_MSG_FILE=$1
ORIGINAL_COMMIT_MSG=$(cat $COMMIT_MSG_FILE)
COMMIT_MSG=$ORIGINAL_COMMIT_MSG

# 커밋메세지 형식 
# emoji type: summary
COMMIT_MESSAGE_REGEX="^[^\s]+ [a-z]+: .+"

format_commit_message() {
  # 이모지, 타입, 요약 추출
  EMOJI=$(echo "$ORIGINAL_COMMIT_MSG" | cut -d ' ' -f1)
  TYPE=$(echo "$ORIGINAL_COMMIT_MSG" | cut -d ' ' -f2 | sed 's/://')
  SUMMARY=$(echo "$ORIGINAL_COMMIT_MSG" | cut -d ':' -f2- | sed 's/^ *//')

  # 이모지 맵
  case "$TYPE" in
    feat) EXPECTED_EMOJI="✨";;
    fix|hotfix) EXPECTED_EMOJI="🐛";;
    build) EXPECTED_EMOJI="🔨";;
    docs) EXPECTED_EMOJI="📝";;
    design) EXPECTED_EMOJI="💄";;
    merge|Merge) EXPECTED_EMOJI="🔀";;
    rename) EXPECTED_EMOJI="🚚";;
    style) EXPECTED_EMOJI="🎨";;
    refactor) EXPECTED_EMOJI="♻️";;
    remove) EXPECTED_EMOJI="🔥";;
    test) EXPECTED_EMOJI="✅";;
    chore) EXPECTED_EMOJI="📦";;
    *)
      echo "------------------------ERROR------------------------"
      echo "🥵 올바른 커밋메세지 타입을 입력해주세요(대소문자구분) 🥵"
      echo "👌 feat,fix,hotfix,build,docs,design,merge,rename,style,refactor,remove,test,chore 👌"
      echo
      exit 1
      ;;
  esac
  
  # 이모지와 타입이 일치하는지 확인
  if [ "$EMOJI" != "$EXPECTED_EMOJI" ]; then
    echo "------------------------ERROR------------------------"
    echo "🥵 이모지와 커밋메세지 타입이 일치하지 않습니다 🥵"
    echo "입력된 이모지: $EMOJI"
    echo "예상된 이모지: $EXPECTED_EMOJI (타입: $TYPE)"
    exit 1
  fi

  COMMIT_MSG="$EMOJI $TYPE: $SUMMARY"
}

validate_commit_message() {
  # 형식 검증
  if ! echo "$COMMIT_MSG" | grep -qE "$COMMIT_MESSAGE_REGEX"; then
    echo
    echo "------------------------ERROR------------------------"
    echo "🥵 커밋 메시지는 'emoji type: summary' 형식이어야 합니다. 띄어쓰기 확인해 주세요!🥵"
    echo "🍙 예시: ✨ feat: add login feature 🍙"
    echo "❗️ (현재 커밋 메시지) $COMMIT_MSG ❗️"
    exit 1
  fi
}

# Merge로 시작하는 커밋은 형식 검사를 생략
if ! echo "$ORIGINAL_COMMIT_MSG" | grep -q "^Merge"; then
  validate_commit_message
  format_commit_message
  echo "$COMMIT_MSG" > "$COMMIT_MSG_FILE"
fi

echo
echo '✈️ ✈️ ✈️ 🛫 wait add jira issue number & Gitmoji 🛬 ✈️ ✈️ ✈️'

BRANCH_NAME=$(git symbolic-ref -q HEAD)
BRANCH_NAME=${BRANCH_NAME##*/} # Remove everything before the last /
ISSUE_TICKET=$(echo "$BRANCH_NAME" | sed -n 's/^\([A-Z]*-[0-9]*\)-\(.*\)$/\1/p')

if [ -n "$ISSUE_TICKET" ]; then
  COMMIT_MSG="$COMMIT_MSG (Jira Ticket : $ISSUE_TICKET)"
  echo "          Jira 티켓 번호: $ISSUE_TICKET / emoji $EMOJI      "
else
  echo "            Jira 티켓 번호: ⚠️ 없어요 ⚠️ / emoji $EMOJI      "
fi

echo "$COMMIT_MSG" > $COMMIT_MSG_FILE
echo
echo "🔆 Thanks for keeping the convention 🔆"
echo